# codon map
codon_map = {"GGA": "G", "GGC": "G", "TTA": "L", "CTG": "L", "TTC": "F", "GAA": "E", "CTC": "L", "CGC": "R", "CAT": "H", "GTG": "V", "GGG": "G",
 "GTC": "V", "CTA": "L", "GCC": "A", "TCG": "S", "CAC": "H", "AAG": "K", "AAT": "N", "CCG": "P", "TGT": "C", "CCC": "P", "CAA": "Q",
 "CGT": "R", "GCG": "A", "ATA": "I", "ACA": "T", "TGC": "C", "CTT": "L", "ACT": "T", "CGA": "R", "TAC": "Y", "AGA": "R", "ACC": "T",
 "GTA": "V", "ACG": "T", "TGG": "W", "AAC": "N", "CAG": "Q", "AGC": "S", "TCC": "S", "GCA": "A", "AGG": "R", "ATG": "M", "GAC": "D",
 "TCA": "S", "TAT": "Y", "ATT": "I", "CCA": "P", "ATC": "I", "AAA": "K", "TTG": "L", "CCT": "P", "GGT": "G", "AGT": "S", "GCT": "A",
 "TTT": "F", "TCT": "S", "GTT": "V", "GAG": "E", "CGG": "R", "GAT": "D", "TAA": "*", "TAG": "*", "TGA": "*"}
# dinucleotides
dinucleotides = ["AA", "AC", "AG", "AT", "CA", "CC", "CG", "CT", "GA", "GC", "GG", "GT", "TA", "TC", "TG", "TT"]
# strict fourfold degenerate codons
fourfold = ["GTT", "GTC", "GTA", "GTG", "CCT", "CCC", "CCA", "CCG", "ACT", "ACC", "ACA", "ACG", "GCT", "GCC", "GCA", "GCG", "GGT", "GGC", "GGA", "GGG"]
# nucleotides
nucleotides = ["A", "C", "G", "T"]
# strict twofold degenerate codons
twofold = ["TTT", "TTC", "TAT", "TAC", "CAT", "CAC", "CAA", "CAG", "AAA", "AAG", "GAT", "GAC", "TGT", "TGC"]
# stop codons
stops = ["TAA", "TAG", "TGA"]
# for each codon, get the set of codons that are 1 mutation away at each position of the codon
one_away_codons = {
    'AAA': {0: ['CAA', 'GAA', 'TAA'], 1: ['ACA', 'AGA', 'ATA'], 2: ['AAC', 'AAG', 'AAT'], },
    'AAC': {0: ['CAC', 'GAC', 'TAC'], 1: ['ACC', 'AGC', 'ATC'], 2: ['AAA', 'AAG', 'AAT'], },
    'AAG': {0: ['CAG', 'GAG', 'TAG'], 1: ['ACG', 'AGG', 'ATG'], 2: ['AAA', 'AAC', 'AAT'], },
    'AAT': {0: ['CAT', 'GAT', 'TAT'], 1: ['ACT', 'AGT', 'ATT'], 2: ['AAA', 'AAC', 'AAG'], },
    'ACA': {0: ['CCA', 'GCA', 'TCA'], 1: ['AAA', 'AGA', 'ATA'], 2: ['ACC', 'ACG', 'ACT'], },
    'ACC': {0: ['CCC', 'GCC', 'TCC'], 1: ['AAC', 'AGC', 'ATC'], 2: ['ACA', 'ACG', 'ACT'], },
    'ACG': {0: ['CCG', 'GCG', 'TCG'], 1: ['AAG', 'AGG', 'ATG'], 2: ['ACA', 'ACC', 'ACT'], },
    'ACT': {0: ['CCT', 'GCT', 'TCT'], 1: ['AAT', 'AGT', 'ATT'], 2: ['ACA', 'ACC', 'ACG'], },
    'AGA': {0: ['CGA', 'GGA', 'TGA'], 1: ['AAA', 'ACA', 'ATA'], 2: ['AGC', 'AGG', 'AGT'], },
    'AGC': {0: ['CGC', 'GGC', 'TGC'], 1: ['AAC', 'ACC', 'ATC'], 2: ['AGA', 'AGG', 'AGT'], },
    'AGG': {0: ['CGG', 'GGG', 'TGG'], 1: ['AAG', 'ACG', 'ATG'], 2: ['AGA', 'AGC', 'AGT'], },
    'AGT': {0: ['CGT', 'GGT', 'TGT'], 1: ['AAT', 'ACT', 'ATT'], 2: ['AGA', 'AGC', 'AGG'], },
    'ATA': {0: ['CTA', 'GTA', 'TTA'], 1: ['AAA', 'ACA', 'AGA'], 2: ['ATC', 'ATG', 'ATT'], },
    'ATC': {0: ['CTC', 'GTC', 'TTC'], 1: ['AAC', 'ACC', 'AGC'], 2: ['ATA', 'ATG', 'ATT'], },
    'ATG': {0: ['CTG', 'GTG', 'TTG'], 1: ['AAG', 'ACG', 'AGG'], 2: ['ATA', 'ATC', 'ATT'], },
    'ATT': {0: ['CTT', 'GTT', 'TTT'], 1: ['AAT', 'ACT', 'AGT'], 2: ['ATA', 'ATC', 'ATG'], },
    'CAA': {0: ['AAA', 'GAA', 'TAA'], 1: ['CCA', 'CGA', 'CTA'], 2: ['CAC', 'CAG', 'CAT'], },
    'CAC': {0: ['AAC', 'GAC', 'TAC'], 1: ['CCC', 'CGC', 'CTC'], 2: ['CAA', 'CAG', 'CAT'], },
    'CAG': {0: ['AAG', 'GAG', 'TAG'], 1: ['CCG', 'CGG', 'CTG'], 2: ['CAA', 'CAC', 'CAT'], },
    'CAT': {0: ['AAT', 'GAT', 'TAT'], 1: ['CCT', 'CGT', 'CTT'], 2: ['CAA', 'CAC', 'CAG'], },
    'CCA': {0: ['ACA', 'GCA', 'TCA'], 1: ['CAA', 'CGA', 'CTA'], 2: ['CCC', 'CCG', 'CCT'], },
    'CCC': {0: ['ACC', 'GCC', 'TCC'], 1: ['CAC', 'CGC', 'CTC'], 2: ['CCA', 'CCG', 'CCT'], },
    'CCG': {0: ['ACG', 'GCG', 'TCG'], 1: ['CAG', 'CGG', 'CTG'], 2: ['CCA', 'CCC', 'CCT'], },
    'CCT': {0: ['ACT', 'GCT', 'TCT'], 1: ['CAT', 'CGT', 'CTT'], 2: ['CCA', 'CCC', 'CCG'], },
    'CGA': {0: ['AGA', 'GGA', 'TGA'], 1: ['CAA', 'CCA', 'CTA'], 2: ['CGC', 'CGG', 'CGT'], },
    'CGC': {0: ['AGC', 'GGC', 'TGC'], 1: ['CAC', 'CCC', 'CTC'], 2: ['CGA', 'CGG', 'CGT'], },
    'CGG': {0: ['AGG', 'GGG', 'TGG'], 1: ['CAG', 'CCG', 'CTG'], 2: ['CGA', 'CGC', 'CGT'], },
    'CGT': {0: ['AGT', 'GGT', 'TGT'], 1: ['CAT', 'CCT', 'CTT'], 2: ['CGA', 'CGC', 'CGG'], },
    'CTA': {0: ['ATA', 'GTA', 'TTA'], 1: ['CAA', 'CCA', 'CGA'], 2: ['CTC', 'CTG', 'CTT'], },
    'CTC': {0: ['ATC', 'GTC', 'TTC'], 1: ['CAC', 'CCC', 'CGC'], 2: ['CTA', 'CTG', 'CTT'], },
    'CTG': {0: ['ATG', 'GTG', 'TTG'], 1: ['CAG', 'CCG', 'CGG'], 2: ['CTA', 'CTC', 'CTT'], },
    'CTT': {0: ['ATT', 'GTT', 'TTT'], 1: ['CAT', 'CCT', 'CGT'], 2: ['CTA', 'CTC', 'CTG'], },
    'GAA': {0: ['AAA', 'CAA', 'TAA'], 1: ['GCA', 'GGA', 'GTA'], 2: ['GAC', 'GAG', 'GAT'], },
    'GAC': {0: ['AAC', 'CAC', 'TAC'], 1: ['GCC', 'GGC', 'GTC'], 2: ['GAA', 'GAG', 'GAT'], },
    'GAG': {0: ['AAG', 'CAG', 'TAG'], 1: ['GCG', 'GGG', 'GTG'], 2: ['GAA', 'GAC', 'GAT'], },
    'GAT': {0: ['AAT', 'CAT', 'TAT'], 1: ['GCT', 'GGT', 'GTT'], 2: ['GAA', 'GAC', 'GAG'], },
    'GCA': {0: ['ACA', 'CCA', 'TCA'], 1: ['GAA', 'GGA', 'GTA'], 2: ['GCC', 'GCG', 'GCT'], },
    'GCC': {0: ['ACC', 'CCC', 'TCC'], 1: ['GAC', 'GGC', 'GTC'], 2: ['GCA', 'GCG', 'GCT'], },
    'GCG': {0: ['ACG', 'CCG', 'TCG'], 1: ['GAG', 'GGG', 'GTG'], 2: ['GCA', 'GCC', 'GCT'], },
    'GCT': {0: ['ACT', 'CCT', 'TCT'], 1: ['GAT', 'GGT', 'GTT'], 2: ['GCA', 'GCC', 'GCG'], },
    'GGA': {0: ['AGA', 'CGA', 'TGA'], 1: ['GAA', 'GCA', 'GTA'], 2: ['GGC', 'GGG', 'GGT'], },
    'GGC': {0: ['AGC', 'CGC', 'TGC'], 1: ['GAC', 'GCC', 'GTC'], 2: ['GGA', 'GGG', 'GGT'], },
    'GGG': {0: ['AGG', 'CGG', 'TGG'], 1: ['GAG', 'GCG', 'GTG'], 2: ['GGA', 'GGC', 'GGT'], },
    'GGT': {0: ['AGT', 'CGT', 'TGT'], 1: ['GAT', 'GCT', 'GTT'], 2: ['GGA', 'GGC', 'GGG'], },
    'GTA': {0: ['ATA', 'CTA', 'TTA'], 1: ['GAA', 'GCA', 'GGA'], 2: ['GTC', 'GTG', 'GTT'], },
    'GTC': {0: ['ATC', 'CTC', 'TTC'], 1: ['GAC', 'GCC', 'GGC'], 2: ['GTA', 'GTG', 'GTT'], },
    'GTG': {0: ['ATG', 'CTG', 'TTG'], 1: ['GAG', 'GCG', 'GGG'], 2: ['GTA', 'GTC', 'GTT'], },
    'GTT': {0: ['ATT', 'CTT', 'TTT'], 1: ['GAT', 'GCT', 'GGT'], 2: ['GTA', 'GTC', 'GTG'], },
    'TAA': {0: ['AAA', 'CAA', 'GAA'], 1: ['TCA', 'TGA', 'TTA'], 2: ['TAC', 'TAG', 'TAT'], },
    'TAC': {0: ['AAC', 'CAC', 'GAC'], 1: ['TCC', 'TGC', 'TTC'], 2: ['TAA', 'TAG', 'TAT'], },
    'TAG': {0: ['AAG', 'CAG', 'GAG'], 1: ['TCG', 'TGG', 'TTG'], 2: ['TAA', 'TAC', 'TAT'], },
    'TAT': {0: ['AAT', 'CAT', 'GAT'], 1: ['TCT', 'TGT', 'TTT'], 2: ['TAA', 'TAC', 'TAG'], },
    'TCA': {0: ['ACA', 'CCA', 'GCA'], 1: ['TAA', 'TGA', 'TTA'], 2: ['TCC', 'TCG', 'TCT'], },
    'TCC': {0: ['ACC', 'CCC', 'GCC'], 1: ['TAC', 'TGC', 'TTC'], 2: ['TCA', 'TCG', 'TCT'], },
    'TCG': {0: ['ACG', 'CCG', 'GCG'], 1: ['TAG', 'TGG', 'TTG'], 2: ['TCA', 'TCC', 'TCT'], },
    'TCT': {0: ['ACT', 'CCT', 'GCT'], 1: ['TAT', 'TGT', 'TTT'], 2: ['TCA', 'TCC', 'TCG'], },
    'TGA': {0: ['AGA', 'CGA', 'GGA'], 1: ['TAA', 'TCA', 'TTA'], 2: ['TGC', 'TGG', 'TGT'], },
    'TGC': {0: ['AGC', 'CGC', 'GGC'], 1: ['TAC', 'TCC', 'TTC'], 2: ['TGA', 'TGG', 'TGT'], },
    'TGG': {0: ['AGG', 'CGG', 'GGG'], 1: ['TAG', 'TCG', 'TTG'], 2: ['TGA', 'TGC', 'TGT'], },
    'TGT': {0: ['AGT', 'CGT', 'GGT'], 1: ['TAT', 'TCT', 'TTT'], 2: ['TGA', 'TGC', 'TGG'], },
    'TTA': {0: ['ATA', 'CTA', 'GTA'], 1: ['TAA', 'TCA', 'TGA'], 2: ['TTC', 'TTG', 'TTT'], },
    'TTC': {0: ['ATC', 'CTC', 'GTC'], 1: ['TAC', 'TCC', 'TGC'], 2: ['TTA', 'TTG', 'TTT'], },
    'TTG': {0: ['ATG', 'CTG', 'GTG'], 1: ['TAG', 'TCG', 'TGG'], 2: ['TTA', 'TTC', 'TTT'], },
    'TTT': {0: ['ATT', 'CTT', 'GTT'], 1: ['TAT', 'TCT', 'TGT'], 2: ['TTA', 'TTC', 'TTG'],},
}
